name: CMake

on:
  push:
    branches: [ "master", "feature/github-actions" ]
  pull_request:
    branches: [ "master", "feature/github-actions" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: 
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Show environment
      run: |
          Get-ChildItem
          cd ..
          Get-ChildItem
    
    - name: Show environment details
      run: Get-ChildItem -Recurse

    - name: Configure CMake
      run: |
          New-Item -Path 'build' -ItemType Directory
          cmake -G"Visual Studio 16 2019" -B build
    
    - name: Show generated VS Project files
      run: |
          cd  build
          Get-ChildItem
    
    - name: Build project
      run: |
          pushd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
          cmd /c "vcvars64.bat&set" |
          foreach {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }
          popd
          cd build
          msbuild VBCPP.sln /property:Configuration=Release
    
    - name: Show build artifact
      run: |
          cd bin/Release
          Get-ChildItem
